spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
                statuses: NOT_FOUND
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, mappings

server:
  port: 8080

