grpc:
  server:
    port: 9090
spring:
  main:
    web-application-type: none

collector:
  kafka:
    close-timeout: 5000ms
    properties:
      "bootstrap.servers": "localhost:9092"
      "key.serializer": "org.apache.kafka.common.serialization.VoidSerializer"
      "value.serializer": "ru.yandex.practicum.kafka.serializer.GenericAvroSerializer"
    topic:
      hubs: "telemetry.hubs.v1"
      sensors: "telemetry.sensors.v1"