spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/commerce_shopping_store"
    username: "postgres"
    password: "postgrespass"
  sql.init.mode: always

server:
  port: 0